ALTER TABLE camera_group_members
    ADD COLUMN IF NOT EXISTS crop_top INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS crop_bottom INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS crop_left INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS crop_right INTEGER NOT NULL DEFAULT 0;
